<?php 

$creativa_options = array(
	'opt-logo' => '',
	'opt-logo-stickyh' => '',
	'opt-logo-mobile' => '',
	'opt-favicon' => '',
	'opt-apple-icons' => '',

	'opt-nav-layout' => '1',
	'opt-nav-side-position' => '1',
	'opt-layout' => '1',
	'opt-content-width' => 1300,
	'opt-boxed-gap' => 60,
	'opt-border-size' => 20,
	'opt-content-padding' => array('padding-top' => '100px', 'padding-bottom' => '100px'),
	'opt-body-bg' => array('background-color' => "#282828"),
	'opt-page-share' => true,
	'opt-back-to-top' => true,

	'opt-navbar-style' => '1',
	'opt-nav-full-width' => true,
	'opt-navbar-height' => 100,
	'opt-header-height' => 150,
	'opt-header-bar-height' => 100,
	'opt-header-bar-gap' => 30,
	'opt-menu-position' => '2',
	'opt-hover-style' => '1',
	'opt-nav-separators' => true,
	'opt-nav-search' => true,
	'opt-secondary-nav' => false,
	'opt-woo-shop-nav-icon' => true,
	'opt-nav-icons-style' => '2',

	'opt-show-sticky-header' => true,
	'opt-sticky-header-height' => 80,
	'opt-sticky-header-style' => '1',
	'opt-show-top-bar' => false,
	'opt-top-bar-text' => '',

	'opt-secondary-nav-style' => '1',

	'opt-title-bar' => true,
	'opt-title-bar-centered' => '1',
	'opt-title-bar-padding' => array('padding-top' => '100px','padding-bottom' => '100px'),
	'opt-title-bar-custom-height' => false,
	'opt-title-bar-height' => array('height' => 0),
	'opt-page-title-bar-align' => '2',
	'opt-page-title-animation' => '0',
	'opt-page-title-animation-content' => '0',
	'opt-animated-canvas-type' => '0',
	'opt-animated-canvas-color' => array('color' => '#000000', 'alpha' => 0.05),
	'opt-animated-canvas-count' => 15,

	'opt-footer-effect' => '1',
	'opt-footer-widget-area' => false,
	'opt-footer-widget-columns' => '3',
	'opt-copyrights' => '<p>&copy; Copyrights 2015 by Creativa. All rights reserved.</p><p>Powered by <a href="http://wordpress.org">WordPress.</a></p>',

	'opt-blog-style' => '1',
	'opt-blog-full-width' => false,
	'opt-show-sidebar' => true,
	'opt-blog-sidebar-position' => '1',
	'opt-show-thumbnail' => true,
	'opt-allow-media-styles' => true,
	'opt-blog-display-media' => '1',
	'opt-excerpts' => true,
	'opt-excerpt-lenght' => 35,
	'opt-display-categories' => true,
	'opt-display-date' => true,
	'opt-display-comments' => true,
	'opt-display-author' => true,

	'opt-blog-page-style' => '1',
	'opt-single-display-media' => true,
	'opt-author-bio' => true,
	'opt-share-buttons' => true,
	'opt-tags' => true,

	'opt-portfolio-layout' => '3',
	'opt-masonry-size' => '2',
	'opt-portfolio-fullwidth' => false,
	'opt-portfolio-items-gap' => 30,
	'opt-portfolio-pagination' => false,
	'opt-portfolio-pper-page' => 5,
	'opt-portfolio-custom-slug' => 'project',
	'opt-portfolio-filtering' => true,
	'opt-portfolio-filtering-pos' => '1',
	'opt-portfolio-sorting' => true,
	'opt-portfolio-style' => '1',
	'opt-porfolio-item-categories' => true,
	'opt-quick-view' => true,
	'opt-like-button' => true,

	'opt-project-layout' => '1',
	'opt-project-layout-med-sidebar' => '1',
	'opt-project-image-gallery' => '2',
	'opt-project-shares' => true,
	'opt-project-prevnext' => true,

	'opt-woo-full-width' => false,
	'opt-woo-shop-layout' => '2',
	'opt-woo-shop-sidebar-position' => '2',
	'opt-woo-shop-items' => 12,
	'opt-woo-shop-items-columns' => 3,
	'opt-shop-welcome' => esc_html__('Shop', 'creativa'),

	'opt-social-facebook-url' => '',
	'opt-social-twitter-url' => '',
	'opt-social-google-plus-url' => '',
	'opt-social-flickr-url' => '',
	'opt-social-linkedin-url' => '',
	'opt-social-pinterest-url' => '',
	'opt-social-instagram-url' => '',
	'opt-social-behance-url' => '',
	'opt-social-dribbble-url' => '',
	'opt-social-tumblr-url' => '',
	'opt-social-youtube-url' => '',
	'opt-social-vimeo-url' => '',
	'opt-social-vine-url' => '',
	'opt-social-lastfm-url' => '',
	'opt-social-deviantart-url' => '',
	'opt-social-digg-url' => '',
	'opt-social-dropbox-url' => '',
	'opt-social-foursquare-url' => '',
	'opt-social-github-url' => '',
	'opt-social-reddit-url' => '',
	'opt-social-skype-url' => '',
	'opt-social-soundcloud-url' => '',
	'opt-social-spotify-url' => '',
	'opt-social-steam-url' => '',
	'opt-social-stumbleupon-url' => '',
	'opt-social-vk-url' => '',
	'opt-social-wordpress-url' => '',
	'opt-social-medium-url' => '',
	'opt-social-twitch-url' => '',
	'opt-social-whatsapp-url' => '',

	'opt-pt-bg' => array('background-color' => "#f7f7f7"),
	'opt-pt-overlay' => '0',
	'opt-navigation-transparency' => 100,

	'opt-ace-editor-css' => '',


	// metaboxes
	'opt-format-video-type' => '1',
	'opt-format-audio-type' => '1',
	'opt-single-subtitle' => '',
	'opt-single-subtitle-display' => true,
	'opt-meta-project-year' => '',
	'opt-meta-project-client' => '',
	'opt-meta-project-custom' => '',
	'opt-meta-project-url' => '',
	'opt-meta-project-url-text' => esc_html__('Launch Project', 'creativa'),
	'opt-portfolio-sel-categories' => '',
	'opt-portfolio-sel-tags' => '',
	'opt-portfolio-sel-authors' => '',
	'opt-portfolio-exc' => false,
	'opt-portfolio-exc-categories' => '',
	'opt-portfolio-exc-tags' => '',
	'opt-portfolio-exc-authors' => '',
	'opt-side-navigation-position' => '1',
	'opt-side-navigation-title' => esc_html__('Pages', 'creativa'),
	'opt-page-subtitle' => '',
	'opt-show-header' => true,
	'opt-show-footer' => true,
	'opt-meta-ace-editor-css' => '',
	'opt-slider-header' => 'none',
	'opt-project-link' => '1',
	'opt-project-link-url' => '',
	'opt-project-link-target' => false,
	'opt-masonry-thumb-size' => '1',
	'opt-meta-select-sidebar' => 'None',
	'opt-meta-template-sidebar-position' => '2',
	'opt-single-clean-meta' => true,
	'opt-meta-custom-menu' => '',
	'opt-custom-page-title' => '',
	'opt-format-quote-content' => '',
	'opt-format-quote-author' => '',
	'opt-format-link-url' => '',
	'opt-format-link-url-title' => '',
	'opt-meta-post-gallery' => '',
	'opt-format-video-url' => '',
	'opt-format-video-embed' => '',
	'opt-format-audio-embed' => '',
	'opt-format-audio-mp3' => '',
	'opt-format-audio-oga' => '',
	'opt-format-audio-author' => '',
	'opt-format-audio-title' => '',
	'opt-meta-project-gallery' => '',

	'opt-google-api-key' => '',
);